---
# handlers file for apache

- name: start apache2
  service:
    name: apache2
    state: started
- name: restart apache2
  service:
    name: apache2
    state: restarted
- name: start httpd
  service:
    name: httpd
    state: started
- name: restart httpd
  service:
    name: httpd
    state: restarted
